package kpi.ye.currencyexchange.currency;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * The {@code Currency} class represents currency code and full name
 * downloaded from openexchangerates.org JSON files. It includes
 * allArgsConstructor, noArgsConstructor, getter, setter, toString,
 * equals and hashCode methods generated by Lombok library.
 *
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Currency {
    private String code;
    private String name;
}
