package kpi.ye.currencyexchange.exchangerate;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * The {@code ExchangeRate} class represents the currency exchange rate
 * downloaded from alphavantage.co JSON files. It includes
 * allArgsConstructor, noArgsConstructor, getter, setter, toString,
 * equals and hashCode methods generated by Lombok library.
 *
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ExchangeRate {
    private BigDecimal exchangeRate;
    private LocalDate date;
    private String apiNote;
}
